"""Plain-language, interactive dashboard (docs/dashboard.html). One self-contained file: no libraries, works offline.

For non-experts: a headline sentence, an animated top-down replay of today's drone mission, a time-lapse of the
field, what the AI decided in plain words, and a "send a drone yourself" demo. All data is simulated and the page
says so. Regenerated by the autopilot every cycle."""

import json

from . import briefing, economics, fleet, gps, imagery
from . import wind as W
from . import model as M
from .config import ROOT, load_policy
from .store import load_farm, load_json, read_jsonl


def _events(audit, limit=14):
    """Translate the machine audit log into sentences a farmer would read."""
    out = []
    for a in audit:
        k = a.get("kind")
        d = a.get("day")
        if k == "cycle":
            t, e, sk = a["targets"], a["executed"], a.get("dropped_by_safety", 0)
            if t == 0:
                line = f"Day {d}: all quiet. The AI found nothing that needed a drone."
            else:
                line = f"Day {d}: the AI found {t} patches that could use help. The drones treated the {e} most urgent ones"
                line += (
                    f" and the other {max(0, t - e - sk)} wait for tomorrow (a drone's battery only covers so many patches a day)."
                    if t - e - sk > 0
                    else "."
                )
                if sk:
                    line += f" {sk} were blocked by safety checks (no-fly area or not enough battery to get home)."
            out.append({"day": d, "icon": "drone", "text": line})
        elif k == "retrain":
            if a.get("promoted"):
                out.append(
                    {
                        "day": None,
                        "icon": "brain",
                        "text": "The AI re-trained itself on fresh field data and the new version passed its test, so it was switched on.",
                    }
                )
            else:
                out.append(
                    {
                        "day": None,
                        "icon": "shield",
                        "text": "The AI tried a new version of itself, but it was no better than the current one, so it kept the old one (automatic safety rollback).",
                    }
                )
        elif k == "model_below_target":
            out.append(
                {
                    "day": None,
                    "icon": "warn",
                    "text": "Heads-up: the AI is less accurate than it should be right now. Simple safety rules (very dry soil, many pests) still trigger the drones.",
                }
            )
        elif k == "incident":
            out.append(
                {
                    "day": None,
                    "icon": "warn",
                    "text": "Something went wrong during a run. The system logged it and carried on the next day.",
                }
            )
        elif k == "sensor_faults":
            out.append(
                {
                    "day": None,
                    "icon": "warn",
                    "text": f"Sensor check: {a.get('flagged', 0)} patches sent suspicious readings (dead, stuck or wildly jumping sensors). "
                    f"The system repaired them from healthy neighbours; {a.get('quarantined', 0)} sensors are flagged for maintenance.",
                }
            )
        elif k == "imagery" and a.get("status") == "updated":
            out.append(
                {
                    "day": None,
                    "icon": "sat",
                    "text": f"New real satellite pass received (Sentinel-2, {a.get('latest')}). The field maps were refreshed.",
                }
            )
        elif k == "twin_initialized_from_satellite":
            out.append(
                {
                    "day": None,
                    "icon": "sat",
                    "text": f"The simulated farm was seeded with this real field's actual patchiness from the {a.get('date')} satellite image.",
                }
            )
        elif k == "grounded_by_wind":
            out.append(
                {
                    "day": None,
                    "icon": "wind",
                    "text": f"Too windy to fly today ({a.get('reason', '')}). The drones stayed on their pads; nothing was lost, the work waits for a calmer day.",
                }
            )
        elif k == "spray_deferred_by_wind":
            out.append(
                {
                    "day": None,
                    "icon": "wind",
                    "text": f"Spraying was postponed for {a.get('patches', 0)} patches: the wind would blow the spray off target. Watering carried on.",
                }
            )
        elif k == "gps_loss":
            out.append(
                {
                    "day": None,
                    "icon": "warn",
                    "text": f"A drone lost its GPS signal after treating {a.get('after_patches', 0)} patches. It stopped spraying, tried to recover the signal, then landed safely where it was. Drones flying below it were sent home so nothing could collide. It is waiting to be picked up.",
                }
            )
        elif k == "queued":
            out.append({"day": None, "icon": "drone", "text": "A flight plan was queued for the ground crew's drones to pick up."})
    return out[-limit:][::-1]


def _satellite(state_dir):
    """Real Sentinel-2 scenes for the dashboard (None if never fetched). Grids are flattened x-major, x100, null = cloud."""
    try:
        scenes = imagery.load_scenes(state_dir)
    except (ValueError, TypeError, KeyError):
        return None
    if not scenes:
        return None
    flat = lambda g, n: [None if g[x][y] is None else round(g[x][y] * 100) for x in range(n) for y in range(n)]  # noqa: E731
    return {
        "analysis": imagery.analyze(scenes),
        "scenes": [
            {"id": s.id, "date": s.date, "valid": s.valid_frac, "ndvi": flat(s.ndvi, s.size), "ndmi": flat(s.ndmi, s.size)} for s in scenes
        ],
    }


def _benchmark():
    f = ROOT / "docs" / "benchmark.json"
    try:
        return json.loads(f.read_text()) if f.exists() else None
    except ValueError:
        return None


def build_data(state_dir=None, policy=None):
    policy = policy or load_policy()
    size = policy["field"]["size"]
    farm = load_farm(policy["field"]["seed"], size, state_dir)
    rows = [r for r in read_jsonl("metrics.jsonl", state_dir) if r.get("ok") and not r.get("skipped")]
    last = rows[-1] if rows else {}
    cells = farm.cells
    stressed = sum(M.true_label(c) for c in cells.values())
    watch = sum(1 for c in cells.values() if not M.true_label(c) and (c.moisture < 0.34 or c.pest > 0.38))
    now = [
        [round(cells[(x, y)].ndvi * 100), round(cells[(x, y)].moisture * 100), round(cells[(x, y)].pest * 100)]
        for x in range(size)
        for y in range(size)
    ]
    mission = load_json("last_mission.json", None, state_dir) or {
        "day": farm.day,
        "size": size,
        "before": now,
        "no_fly": policy["no_fly_cells"],
        "missions": [],
    }
    audit = [dict(a, day=a.get("day")) for a in read_jsonl("audit.jsonl", state_dir)[-60:]]
    for a in audit:  # attach the day to events that don't carry one
        if a.get("kind") == "cycle":
            a["day"] = a.get("day")
    data = {
        "size": size,
        "day": farm.day,
        "now": now,
        "mission": mission,
        "history": load_json("field_history.json", [], state_dir),
        "metrics": [
            {
                k: r.get(k)
                for k in (
                    "day",
                    "accuracy",
                    "recall",
                    "water_saved_pct",
                    "chem_saved_pct",
                    "yield_index",
                    "targets",
                    "executed",
                    "sorties",
                    "sensors_flagged",
                    "sensors_quarantined",
                    "rain_mm",
                    "traffic_min_ratio",
                    "traffic_mode",
                    "launch_stagger_s",
                    "fleet_energy_wh",
                    "charged_between_flights_wh",
                    "overnight_charge_wh",
                    "overnight_charge_hours",
                    "battery_health_min",
                    "soc_min_pct",
                    "wind_ms",
                    "gust_ms",
                    "wind_from_deg",
                    "grounded_by_wind",
                    "spray_deferred",
                    "gps_losses",
                    "gps_patches_deferred",
                    "drones_grounded",
                )
            }
            for r in rows[-60:]
        ],
        "weather": load_json("weather.json", None, state_dir),
        "fleet": {**fleet.charging(policy), "drones": (load_json("fleet.json", None, state_dir) or {}).get("drones", [])},
        "satellite": _satellite(state_dir),
        "benchmark": _benchmark(),
        "events": _events(audit),
        "kpi": {
            "healthy_pct": round(100 * (1 - (stressed + watch) / len(cells))),
            "stressed": stressed,
            "watch": watch,
            "cells": len(cells),
            "water": last.get("water_saved_pct", 0),
            "chem": last.get("chem_saved_pct", 0),
            "accuracy": last.get("accuracy"),
            "recall": last.get("recall"),
            "yield": last.get("yield_index", 1),
        },
        "policy": {
            "autonomy": policy["autonomy_level"],
            "kill": bool(policy["kill_switch"]),
            "drones": policy["fleet"]["drones"],
            "battery_wh": policy["fleet"]["battery_wh"],
            "pad_spacing_m": policy["fleet"].get("pad_spacing_m", 40),
            "h_clear": policy["fleet"].get("horizontal_clearance_m", 20),
            "v_clear": policy["fleet"]["min_separation_m"],
            "speed_ms": policy["fleet"].get("speed_ms", 10),
            "wind_lim": W.limits(policy),
            "gps_grace_s": gps.cfg(policy)["grace_s"],
            "gps_recovery_days": gps.cfg(policy)["recovery_days"],
            "cell_m": policy["field"]["cell_m"],
            "thr": policy["thresholds"],
        },
    }

    bench = data["benchmark"]
    if bench:
        try:
            rows = economics.compare(bench, policy, policy["fleet"]["drones"])
            data["economics"] = {
                "rows": rows,
                "payback_days": economics.payback_days(policy, bench, policy["fleet"]["drones"]),
                "payback_vs_smart_days": economics.payback_days(policy, bench, policy["fleet"]["drones"], "triggered"),
                "hectares": rows[0]["hectares"],
            }
        except (KeyError, ZeroDivisionError):
            data["economics"] = None
    else:
        data["economics"] = None
    data["briefing"] = briefing.sentences(data)
    return data


def render(state_dir=None, policy=None):
    data = json.dumps(build_data(state_dir, policy), separators=(",", ":"))
    return PAGE.replace("/*__DATA__*/null", data)


def write(state_dir=None):
    out = ROOT / "docs" / "dashboard.html"
    out.write_text(render(state_dir))
    return out


PAGE = r"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>AgriDroneAI – Farm Dashboard</title>
<style>
:root{--bg:#f4f7f1;--card:#fff;--fg:#17261c;--mut:#5d6b61;--bd:#dfe6da;--acc:#2e8b4f;--acc2:#e8f4ec;--warn:#c2410c;--blue:#2563eb;--shadow:0 1px 2px rgba(0,0,0,.05),0 6px 18px rgba(20,50,30,.06)}
@media(prefers-color-scheme:dark){:root:not([data-theme=light]){--bg:#0f1812;--card:#17231b;--fg:#e8f1ea;--mut:#9db0a2;--bd:#27382c;--acc:#5fd085;--acc2:#1c3125;--warn:#fb923c;--blue:#7aa2ff;--shadow:none}}
:root[data-theme=dark]{--bg:#0f1812;--card:#17231b;--fg:#e8f1ea;--mut:#9db0a2;--bd:#27382c;--acc:#5fd085;--acc2:#1c3125;--warn:#fb923c;--blue:#7aa2ff;--shadow:none}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:16px/1.5 system-ui,-apple-system,Segoe UI,sans-serif}
.wrap{max-width:1100px;margin:0 auto;padding:16px}
.banner{background:var(--acc2);border:1px solid var(--bd);border-radius:12px;padding:8px 12px;font-size:13px;color:var(--mut);display:flex;gap:8px;align-items:center;flex-wrap:wrap}
.banner b{color:var(--fg)}
header{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;margin:18px 0 10px;flex-wrap:wrap}
h1{font-size:26px;margin:0}h2{font-size:18px;margin:0 0 4px}.sub{color:var(--mut);font-size:14px}
.hero{background:linear-gradient(135deg,var(--acc2),var(--card));border:1px solid var(--bd);border-radius:18px;padding:20px;box-shadow:var(--shadow)}
.hero p{font-size:20px;line-height:1.4;margin:0 0 14px;max-width:760px}
.tiles{display:grid;gap:10px;grid-template-columns:repeat(auto-fit,minmax(180px,1fr))}
.tile{background:var(--card);border:1px solid var(--bd);border-radius:14px;padding:12px 14px}
.tile .v{font-size:30px;font-weight:700;letter-spacing:-.5px}.tile .k{font-weight:600}.tile .d{color:var(--mut);font-size:13px}
.card{background:var(--card);border:1px solid var(--bd);border-radius:18px;padding:16px;box-shadow:var(--shadow);margin-top:14px}
.two{display:grid;gap:14px;grid-template-columns:minmax(0,1.25fr) minmax(0,1fr);align-items:start}
@media(max-width:820px){.two{grid-template-columns:1fr}}
canvas{width:100%;border-radius:12px;background:#27402e;display:block;touch-action:manipulation}
.ctl{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0 2px;align-items:center}
button,.chip{font:inherit;font-size:14px;border:1px solid var(--bd);background:var(--card);color:var(--fg);border-radius:999px;padding:7px 14px;cursor:pointer}
button:hover,.chip:hover{border-color:var(--acc)}button.on,.chip.on{background:var(--acc);color:#fff;border-color:var(--acc)}
button:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid var(--blue);outline-offset:2px}
.legend{display:flex;gap:12px;flex-wrap:wrap;font-size:13px;color:var(--mut);margin-top:8px}
.legend i{display:inline-block;width:12px;height:12px;border-radius:3px;vertical-align:-1px;margin-right:5px}
.drones{display:grid;gap:8px;margin-top:10px}
.dr{display:grid;grid-template-columns:auto 1fr;gap:2px 10px;align-items:center;background:var(--bg);border-radius:12px;padding:8px 10px;font-size:14px}
.dr .n{font-weight:700}.bat{height:8px;background:var(--bd);border-radius:6px;overflow:hidden;margin-top:3px}.bat>div{height:100%;background:var(--acc);transition:width .2s}
.feed{list-style:none;margin:0;padding:0;display:grid;gap:8px}.feed li{display:flex;gap:10px;align-items:flex-start;padding:10px;border-radius:12px;background:var(--bg);font-size:14px}
.ico{flex:none;width:26px;height:26px;border-radius:50%;display:grid;place-items:center;background:var(--acc2);font-size:14px}
.bar{height:14px;background:var(--bd);border-radius:8px;overflow:hidden;margin:4px 0 10px}.bar>div{height:100%;border-radius:8px}
.row{display:flex;justify-content:space-between;font-size:14px;gap:8px}
.tip{position:fixed;pointer-events:none;background:#111c;backdrop-filter:blur(4px);color:#fff;padding:6px 10px;border-radius:8px;font-size:13px;z-index:9;max-width:230px;display:none}
details{border-top:1px solid var(--bd);padding:10px 0}details:first-of-type{border-top:0}summary{cursor:pointer;font-weight:600}details p{color:var(--mut);margin:8px 0 0;font-size:15px}
.toast{position:fixed;left:50%;bottom:20px;transform:translateX(-50%);background:var(--fg);color:var(--bg);padding:10px 16px;border-radius:12px;font-size:14px;display:none;z-index:10}
input[type=range]{width:100%;accent-color:var(--acc)}
.spark{width:100%;height:46px}
.brow{display:grid;grid-template-columns:minmax(120px,1.1fr) 2fr 2fr;gap:6px 12px;align-items:center;padding:8px 0;border-top:1px solid var(--bd);font-size:14px}
.brow:first-child{border-top:0}.brow .cap{font-size:12px;color:var(--mut)}.brow .b{height:10px;background:var(--bd);border-radius:6px;overflow:hidden;margin-top:3px}.brow .b>div{height:100%;border-radius:6px}
.ico.sat{background:#e0ecff}
.brow.hl{background:var(--acc2);border-radius:10px;padding:8px 10px}
@media(max-width:560px){.brow{grid-template-columns:1fr 1fr}.brow>b{grid-column:1/-1}}
@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
</style></head><body><div class="wrap">
<div class="banner" role="note">🧪 <b>This is a simulated farm.</b> Everything here comes from a computer simulation, not a real field. Real drones and sensors can be connected later.</div>
<header><div><h1>🌾 AgriDroneAI</h1><div class="sub" id="status"></div></div><button id="theme" aria-label="Toggle dark mode">🌓 Light / dark</button></header>

<section class="card" id="briefCard" style="display:none"><h2>📰 Today's briefing</h2><ul class="feed" id="brief" style="margin-top:10px"></ul></section>
<section class="hero" aria-live="polite"><p id="headline"></p><div class="tiles" id="tiles"></div></section>
<section class="card" id="briefCard" style="display:none"><h2>📰 Today's briefing</h2><div class="sub">Written by the system from its own records. Ask it anything from a terminal: <code>agridrone ask "why was the fleet grounded?"</code></div><ul class="feed" id="brief" style="margin-top:10px"></ul></section>

<section class="card"><h2>🚁 Watch today's drone mission</h2>
<div class="sub">A top-down view of the farm. Each square is a patch of crop. Each drone has its own launch pad (A, B, C…). They fly out, hover over patches that need help, and water or spray them, then land and recharge. The faint ring around each drone is the safe distance other drones must keep.</div>
<div class="two" style="margin-top:12px"><div>
<canvas id="live" aria-label="Animated drone mission over the farm"></canvas>
<div class="ctl"><button id="play" class="on">⏸ Pause</button><button id="restart">↺ Replay</button>
<button id="s1" class="chip on">1×</button><button id="s2" class="chip">2×</button><button id="s4" class="chip">4×</button>
<button id="dispatch" class="chip">👆 Send a drone yourself</button></div>
<div class="legend"><span><i style="background:#3f9b4d"></i>healthy</span><span><i style="background:#d6c44a"></i>needs attention</span><span><i style="background:#9b6a3a"></i>struggling</span><span><i style="background:#3b82f6"></i>💧 watering</span><span><i style="background:#f59e0b"></i>🌫 pest spray</span><span><i style="background:repeating-linear-gradient(45deg,#c2410c,#c2410c 2px,transparent 2px,transparent 5px)"></i>no-fly zone</span></div>
</div><div><h2 style="font-size:16px">Drone crew</h2><div class="drones" id="drones"></div>
<p class="sub" id="missionNote" style="margin-top:10px"></p></div></div></section>

<div class="two">
<section class="card"><h2>⏱ Field time-lapse</h2><div class="sub">Drag the slider to see how the farm changed day by day.</div>
<canvas id="lapse" style="margin-top:10px" aria-label="Field over time"></canvas>
<div class="ctl"><span class="chip on" data-mode="health">Crop health</span><span class="chip" data-mode="water">Soil moisture</span><span class="chip" data-mode="pests">Pests</span><button id="lapsePlay">▶ Play</button></div>
<input type="range" id="slider" min="0" max="0" value="0" aria-label="Day"><div class="row"><span id="dayLabel"></span><span class="sub">hover a square for details</span></div></section>
<section class="card"><h2>💬 What the AI did</h2><div class="sub">In plain words, newest first.</div><ul class="feed" id="feed" style="margin-top:10px"></ul></section>
</div>

<section class="card" id="satCard" style="display:none"><h2>🛰 Real satellite view</h2>
<div class="sub"><b>Real data, not simulated.</b> Sentinel-2 images of the actual field. Clouds are removed before anything is averaged.</div>
<div class="two" style="margin-top:12px"><div>
<canvas id="sat" aria-label="Satellite map of the field"></canvas>
<div class="ctl"><span class="chip on" data-sat="ndvi">Crop vigor</span><span class="chip" data-sat="ndmi">Leaf water</span></div>
<input type="range" id="satSlider" min="0" max="0" value="0" aria-label="Satellite image date"><div class="row"><span id="satDay"></span><span class="sub">hover a square for details</span></div>
<div class="legend"><span><i style="background:#9b6a3a"></i>low</span><span><i style="background:#d6c44a"></i>medium</span><span><i style="background:#3f9b4d"></i>high</span><span><i style="background:repeating-linear-gradient(45deg,#8a8f96,#8a8f96 2px,transparent 2px,transparent 5px)"></i>cloud / no data</span><span>◯ check first</span></div>
</div><div><div id="satText"></div><div class="sub" style="margin-top:12px">Average crop vigor on each satellite pass</div><svg class="spark" id="satSpark" viewBox="0 0 300 46" preserveAspectRatio="none"></svg><div class="sub" id="satSparkLbl"></div></div></div></section>
<div class="two">
<section class="card"><h2>🛡 Airspace safety</h2><div id="air"></div></section>
<section class="card"><h2>🔋 Fleet &amp; charging</h2><div id="fleetCard"></div></section>
</div>
<section class="card"><h2>🌬 Wind &amp; GPS safety</h2><div class="two" style="margin-top:6px"><div id="windCard"></div><div id="gpsCard"></div></div></section>
<div class="two">
<section class="card"><h2>🌦 Weather</h2><div class="sub" id="wxsub"></div><div id="wx" style="margin-top:8px"></div></section>
<section class="card"><h2>📡 Sensors &amp; workload</h2><div id="sens"></div>
<div class="sub" style="margin-top:12px">Patches waiting for a drone (each day)</div><svg class="spark" id="backlog" viewBox="0 0 300 46" preserveAspectRatio="none"></svg></section>
</div>
<section class="card" id="moneyCard" style="display:none"><h2>💰 Does it pay?</h2><div class="sub" id="moneySub"></div><div id="money" style="margin-top:8px"></div><p class="sub" id="moneyNote" style="margin-top:10px"></p></section>
<section class="card" id="benchCard" style="display:none"><h2>🏁 How well does it actually work?</h2><div class="sub" id="benchSub"></div><div id="bench" style="margin-top:8px"></div><p class="sub" id="benchNote" style="margin-top:10px"></p></section>
<div class="two">
<section class="card"><h2>💧 Resources saved</h2><div class="sub">Compared with watering and spraying the whole farm on a fixed schedule.</div><div style="margin-top:12px" id="saves"></div>
<div class="sub" style="margin-top:6px">Trend of crop health (higher is better)</div><svg class="spark" id="spark" viewBox="0 0 300 46" preserveAspectRatio="none"></svg></section>
<section class="card"><h2>🤔 New here? Quick answers</h2>
<details open><summary>What am I looking at?</summary><p>A pretend farm of 576 small patches. Sensors and drones measure how green (healthy) each patch is, how wet the soil is, and how many pests there are. An AI decides where the drones should go.</p></details>
<details><summary>How do the drones avoid crashing into each other?</summary><p>Four layers. Each drone has its own launch pad, spaced well apart. Drones flying at the same time cruise at different heights. Before any takeoff, the whole plan is replayed second by second in 3D, and it is rejected if any two drones would ever be both too close sideways <i>and</i> too close vertically (this catches the risky moments of climbing and landing). If a safe overlap can't be found, the drones simply fly one at a time.</p></details>
<details><summary>What happens when it is windy?</summary><p>Wind changes how much battery a flight uses (a headwind costs a lot, a tailwind saves some), and it is stronger higher up, so the highest flight layer gives up first. Above a safe wind speed nothing flies at all, and spraying has its own lower limit because wind blows the spray off target. Gusty air also makes the drones keep a bigger safe distance from each other. Anything postponed is simply done on a calmer day.</p></details>
<details><summary>What if a drone loses its GPS?</summary><p>Without GPS a drone cannot find its way home, so it does not try. It instantly stops spraying, waits a few seconds in case the signal comes back, and if not, lands safely right where it is. Any drone flying <i>below</i> it is sent home immediately so nothing can fall on it. The landed drone is picked up later, and its unfinished work is rescheduled.</p></details>
<details><summary>Do the drones recharge?</summary><p>Yes. Each drone has a battery that is tracked day to day. Between flights it recharges on its pad (or swaps to a spare pack), and overnight everything charges to full. A slow charger means later flights can cover less, so the planner budgets each flight from what the battery can really hold. Batteries also wear out slowly with use.</p></details>
<details><summary>Why do drones skip some patches?</summary><p>Safety first: they never fly into no-fly zones, never go if the battery wouldn't leave a safe reserve, and each drone flies at its own height so they can't collide.</p></details>
<details><summary>What does "AI accuracy" mean?</summary><p>How often the AI correctly tells a struggling patch from a healthy one. Because struggling patches are rare, we measure it fairly: it gets credit for catching the sick ones <i>and</i> for not raising false alarms.</p></details>
<details><summary>Does it run by itself?</summary><p>Yes. A scheduled program runs one "day" automatically, saves what it did, re-trains the AI when conditions change, and writes weekly reports. A human can switch everything off with one setting (the kill switch).</p></details>
<details><summary>Is any of this real?</summary><p>No. It's a simulation, so numbers like "water saved" show what the approach could do, not proven field results.</p></details></section>
</div>
<p class="sub" style="text-align:center;margin:18px 0">Updated automatically every day · <span id="stamp"></span></p>
</div><div class="tip" id="tip"></div><div class="toast" id="toast" role="status"></div>
<script>
const D=/*__DATA__*/null;
const $=s=>document.querySelector(s),N=D.size,CM=D.policy.cell_m;
const nofly=new Set(D.mission.no_fly.map(c=>c[0]+","+c[1]));
const idx=(x,y)=>x*N+y;
const css=v=>getComputedStyle(document.documentElement).getPropertyValue(v).trim();
// ---------- headline + tiles ----------
const k=D.kpi;
$("#status").textContent=`Day ${D.day} · autonomy: ${D.policy.autonomy} · kill switch: ${D.policy.kill?"ENGAGED":"off"} · ${D.policy.drones} drones`;
const bad=k.stressed/k.cells,ok=k.healthy_pct/100;
const mood=bad>0.15?"under real stress":bad>0.04?"having some trouble spots":ok>=0.85?"in great shape":"fine overall, with some patches worth watching";
$("#headline").innerHTML=`Day ${D.day}: your farm is <b>${mood}</b>. <b>${k.healthy_pct}%</b> of the land is fully healthy, <b>${k.watch}</b> patches are worth keeping an eye on, and <b>${k.stressed}</b> are struggling and need care. The drone crew handled <b>${D.metrics.length?D.metrics[D.metrics.length-1].executed:0}</b> patches today.`;
const pct=v=>v==null?"–":Math.round(v*100)+"%";
const tiles=[["🌱 Healthy land",k.healthy_pct+"%","Patches with no water or pest worry at all. Yellow = watch, brown = struggling."],
["💧 Water saved",Math.round(k.water)+"%","Less water than a fixed whole-farm schedule (simulated)."],
["🧴 Chemicals saved",Math.round(k.chem)+"%","Less spray, because only infested patches get treated."],
["🧠 AI accuracy",pct(k.accuracy),"How fairly the AI tells sick from healthy patches. Catches "+pct(k.recall)+" of the sick ones."]];
$("#tiles").innerHTML=tiles.map(t=>`<div class="tile" title="${t[2]}"><div class="k">${t[0]}</div><div class="v">${t[1]}</div><div class="d">${t[2]}</div></div>`).join("");
$("#stamp").textContent="data for day "+D.day;
// ---------- colours ----------
function cellColor(c,mode){const [n,m,p]=c;
 if(mode==="water"){const t=Math.max(0,Math.min(1,(m-5)/50));return `hsl(${30+t*190},65%,${52-t*8}%)`}
 if(mode==="pests"){const t=Math.max(0,Math.min(1,p/80));return `hsl(${110-t*110},65%,${40+t*4}%)`}
 const bad=(m<28)||(p>50),mild=(m<34)||(p>38);
 if(bad)return "#9b6a3a"; if(mild)return "#d6c44a";
 const t=Math.max(0,Math.min(1,(n-40)/50));return `hsl(${95+t*25},${48+t*10}%,${44-t*8}%)`}
function describe(c){const [n,m,p]=c,out=[];
 if(m<28)out.push("very dry soil – needs water");else if(m<34)out.push("soil getting dry");
 if(p>50)out.push("heavy pest pressure – needs spray");else if(p>38)out.push("some pests spotted");
 return (out.length?out.join(", "):"healthy and well-watered")+` (greenness ${n}%, moisture ${m}%, pests ${p}%)`}
// ---------- canvas helper ----------
function fit(cv,w){const dpr=window.devicePixelRatio||1,W=Math.min(w||cv.parentElement.clientWidth,720);cv.width=W*dpr;cv.height=W*dpr;cv.style.height=W+"px";const g=cv.getContext("2d");g.setTransform(dpr,0,0,dpr,0,0);return {g,W,s:W/N}}
function drawField(g,s,cells,mode,hl){
 for(let x=0;x<N;x++)for(let y=0;y<N;y++){const px=x*s,py=(N-1-y)*s;g.fillStyle=cellColor(cells[idx(x,y)],mode);g.fillRect(px+.5,py+.5,s-1,s-1)
  if(nofly.has(x+","+y)){g.fillStyle="rgba(194,65,12,.55)";g.fillRect(px,py,s,s);g.strokeStyle="rgba(255,255,255,.55)";g.lineWidth=1;g.beginPath();g.moveTo(px,py+s);g.lineTo(px+s,py);g.stroke()}}
 if(hl){g.strokeStyle="#fff";g.lineWidth=2;g.strokeRect(hl[0]*s+1,(N-1-hl[1])*s+1,s-2,s-2)}}
const P=(x,y,s)=>[x*s+s/2,(N-1-y)*s+s/2];
// ---------- LIVE MISSION ----------
const live=$("#live");let L,speed=1,playing=true,tNow=0,dispatchMode=false,demo=[],pending=0;
const names=["Drone A","Drone B","Drone C","Drone D","Drone E"],colors=["#ffffff","#7dd3fc","#fde68a","#fca5a5","#c4b5fd"];
const SPEED=2.4,DWELL=1.4,TAKEOFF=.8; // cells per second, seconds hovering
const PADC=(D.policy.pad_spacing_m||40)/D.policy.cell_m,RT=SPEED*D.policy.cell_m/(D.policy.speed_ms||5),CLR=(D.policy.h_clear||20)/D.policy.cell_m; // replay runs ~RT times faster than real time
function buildPlan(m,idx0){ // timeline of waypoints for one drone: its own pad -> targets (+ detours) -> back to its pad (or down in a field)
 const fate=m.fate||null,tg=(fate&&fate.status!=="completed")?m.targets.slice(0,fate.flown_targets):m.targets;
 const pad=(m.pad!=null&&m.pad>=0)?m.pad:m.drone,base=[pad*PADC,0,null];
 const pts=[base].concat(tg.map(t=>[t[0],t[1],t[2]])),segs=[];let t=TAKEOFF,endPos=null;
 for(let i=1;i<pts.length;i++){const via=pts[i][2]==="via",d=Math.hypot(pts[i][0]-pts[i-1][0],pts[i][1]-pts[i-1][1]);const t1=t+d/SPEED,dw=via?0:DWELL;segs.push({a:pts[i-1],b:pts[i],t0:t,t1,hover:t1+dw,act:via?null:pts[i][2],via});t=t1+dw}
 const last=pts[pts.length-1];
 if(fate&&fate.status==="gps_lost"){segs.push({a:last,b:last,t0:t,t1:t+1.8,hover:t+1.8,act:null,gpsloss:true});t+=1.8;endPos=[last[0],last[1]]}
 else{const d=Math.hypot(last[0]-base[0],last[1]-base[1]);segs.push({a:last,b:base,t0:t,t1:t+d/SPEED,hover:t+d/SPEED,act:null,ret:true});t+=d/SPEED;
  const hold=(m.hold||0)/RT;if(hold>0.02){segs.push({a:base,b:base,t0:t,t1:t+hold,hover:t+hold,act:null,holding:true});t+=hold}}
 return {drone:m.drone,alt:m.alt,segs,end:t+.6,idx:idx0,trail:[],start:0,pad,t0r:(m.t0||0)/RT,sortie:m.sortie||0,energy:m.energy_wh||0,soc:m.soc||null,endPos,fate}}
function shiftPlan(p,off){p.segs.forEach(s=>{s.t0+=off;s.t1+=off;s.hover+=off});p.end+=off;p.start+=off;return p}
const SWAP=2.5; // seconds shown for a battery swap between flights
let plans=[],display=[],fx=[],doneCells=new Set();
function reset(){tNow=0;display=D.mission.before.map(c=>c.slice());doneCells=new Set();fx=[];
 const bys={};D.mission.missions.filter(m=>!(m.fate&&m.fate.status==="cancelled")).forEach(m=>{(bys[m.sortie||0]=bys[m.sortie||0]||[]).push(buildPlan(m,m.drone))});
 plans=[];let off=0;Object.keys(bys).sort((x,y)=>x-y).forEach(k=>{const g=bys[k];g.forEach(p=>shiftPlan(p,off+p.t0r));plans.push(...g);off=Math.max(...g.map(p=>p.end))+SWAP});
 plans=plans.concat(demo);plans.forEach(p=>p.trail=[])}
function posAt(p,t){ // -> {x,y,state,msg,prog}
 if(t<p.start)return{x:p.pad*PADC,y:0,air:0,msg:"Waiting",idle:true};
 if(t<p.start+TAKEOFF)return{x:p.pad*PADC,y:0,air:(t-p.start)/TAKEOFF,msg:"Taking off…"};
 for(const s of p.segs){if(s.gpsloss){if(t<s.hover)return{x:s.b[0],y:s.b[1],air:Math.max(0,1-(t-s.t0)/(s.t1-s.t0)),msg:"⚠ GPS lost: spraying stopped, landing safely where it is",gpsloss:true};continue}
  if(s.holding){if(t<s.hover)return{x:s.b[0],y:s.b[1],air:1,msg:"Circling above its pad until the airspace is clear to land"};continue}
  if(t<s.t1){const u=(t-s.t0)/(s.t1-s.t0);return{x:s.a[0]+(s.b[0]-s.a[0])*u,y:s.a[1]+(s.b[1]-s.a[1])*u,air:1,msg:s.ret?(p.fate&&p.fate.status==="recalled"?"↩ Ordered home: a drone above lost GPS":"Flying home…"):s.via?"Flying around the no-fly zone…":`Flying to patch (${s.b[0]},${s.b[1]})`}}
  if(t<s.hover)return{x:s.b[0],y:s.b[1],air:1,act:s.act,hov:(t-s.t1)/DWELL,msg:s.act==="spray"?`Spraying pests at (${s.b[0]},${s.b[1]})`:`Watering patch (${s.b[0]},${s.b[1]})`,cell:s.b}}
 return{x:p.endPos?p.endPos[0]:p.pad*PADC,y:p.endPos?p.endPos[1]:0,air:p.endPos?0:Math.max(0,1-(t-(p.end-.6))/.6),msg:t>=p.end?(p.endPos?"⚠ Down in the field, waiting to be picked up":"Landed ✔ mission complete"):"Landing…",landed:t>=p.end,gpsloss:!!p.endPos}}
function frame(dt){
 if(playing)tNow+=dt*speed;const {g,W,s}=L;drawField(g,s,display,"health");
 // one launch pad per drone, spaced apart so climbs and descents never share a column
 const padN=Math.max(D.policy.drones,...plans.map(p=>p.pad+1));for(let i=0;i<padN;i++){const [hx,hy]=P(i*PADC,0,s);g.fillStyle="rgba(255,255,255,.88)";g.beginPath();g.arc(hx,hy,s*.42,0,7);g.fill();g.fillStyle="#17261c";g.font=`bold ${s*.5}px system-ui`;g.textAlign="center";g.textBaseline="middle";g.fillText(String.fromCharCode(65+i),hx,hy)}
 const wd=D.mission.wind||[0,0,270];
 if(wd[0]>0.3){const ang=(wd[2]+180)*Math.PI/180,ax=Math.sin(ang),ay=-Math.cos(ang),cx=L.W-s*3.4,cy=s*2.6,ln=Math.min(s*3.2,s*0.55*wd[0]+s*1.2);
  g.strokeStyle="rgba(255,255,255,.9)";g.fillStyle="rgba(255,255,255,.9)";g.lineWidth=2.2;g.beginPath();g.moveTo(cx-ax*ln/2,cy-ay*ln/2);g.lineTo(cx+ax*ln/2,cy+ay*ln/2);g.stroke();
  const hx=cx+ax*ln/2,hy=cy+ay*ln/2;g.beginPath();g.moveTo(hx,hy);g.lineTo(hx-ax*s*.9+ay*s*.5,hy-ay*s*.9-ax*s*.5);g.lineTo(hx-ax*s*.9-ay*s*.5,hy-ay*s*.9+ax*s*.5);g.closePath();g.fill();
  g.font=`600 ${Math.max(10,s*.6)}px system-ui`;g.textAlign="center";g.textBaseline="top";g.fillText(`💨 ${wd[0]} m/s`,cx,cy+s*1.3)}
 let alive=0;
 plans.forEach(p=>{const st=posAt(p,tNow);if(!st.landed)alive++;if(st.idle)return;
  const col=colors[p.idx%colors.length],[px,py]=P(st.x,st.y,s);
  if(playing&&!st.landed&&(!p.trail.length||Math.hypot(p.trail[p.trail.length-1][0]-px,p.trail[p.trail.length-1][1]-py)>2))p.trail.push([px,py]);
  g.strokeStyle=col;g.globalAlpha=.55;g.lineWidth=2;g.setLineDash([4,4]);g.beginPath();p.trail.forEach((q,i)=>i?g.lineTo(q[0],q[1]):g.moveTo(q[0],q[1]));g.stroke();g.setLineDash([]);g.globalAlpha=1;
  // treat cell when hover is half done
  if(st.act&&st.hov>.35){const key=st.cell[0]+","+st.cell[1];if(!doneCells.has(key)){doneCells.add(key);if(!p.demo)display[idx(st.cell[0],st.cell[1])]=D.now[idx(st.cell[0],st.cell[1])].slice();else{const c=display[idx(st.cell[0],st.cell[1])];if(st.act==="irrigate")c[1]=48;else c[2]=8}}}
  if(st.act&&!st.landed){const n=3;for(let i=0;i<n;i++){const ph=((tNow*1.6+i/n)%1);
    if(st.act==="irrigate"){g.fillStyle=`rgba(59,130,246,${1-ph})`;g.beginPath();g.arc(px+(i-1)*s*.35,py+s*.3+ph*s*1.1,s*.16,0,7);g.fill()}
    else{g.fillStyle=`rgba(245,158,11,${.55*(1-ph)})`;g.beginPath();g.arc(px,py+s*.2,s*(.4+ph*1.1),0,7);g.fill()}}}
  if(st.gpsloss){g.strokeStyle="#ef4444";g.lineWidth=2.5;g.beginPath();g.arc(px,py,s*1.1,0,7);g.stroke();g.fillStyle="#ef4444";g.font=`bold ${s*.9}px system-ui`;g.textAlign="center";g.textBaseline="bottom";g.fillText("⚠",px,py-s*1.2)}
  if(st.air>.4){g.strokeStyle="rgba(255,255,255,.32)";g.lineWidth=1;g.setLineDash([2,3]);g.beginPath();g.arc(px,py,CLR*s,0,7);g.stroke();g.setLineDash([])} // required clear distance around each drone
  // drone: shadow (offset grows with altitude), body, spinning rotors
  const lift=st.air*(p.alt/30)*s*.35;g.fillStyle="rgba(0,0,0,.28)";g.beginPath();g.ellipse(px+lift*.5,py+lift*.7,s*.8,s*.4,0,0,7);g.fill();
  const r=s*.9;g.save();g.translate(px,py-lift*.3);g.fillStyle=col;g.strokeStyle="#111";g.lineWidth=1.5;
  for(const [ox,oy] of [[-1,-1],[1,-1],[1,1],[-1,1]]){g.beginPath();g.moveTo(0,0);g.lineTo(ox*r,oy*r);g.stroke();g.save();g.translate(ox*r,oy*r);g.rotate(tNow*28);g.fillStyle="rgba(255,255,255,.75)";g.fillRect(-r*.55,-1.2,r*1.1,2.4);g.fillRect(-1.2,-r*.55,2.4,r*1.1);g.restore()}
  g.beginPath();g.arc(0,0,r*.42,0,7);g.fillStyle=col;g.fill();g.stroke();g.restore();
  g.fillStyle="#fff";g.font=`600 ${Math.max(10,s*.55)}px system-ui`;g.textAlign="center";g.textBaseline="bottom";g.fillText(p.demo?"★":String.fromCharCode(65+p.idx),px,py-r-lift*.3-2)});
 renderDrones();
 if(!alive&&playing&&pending++>90){pending=0;reset()}else if(alive)pending=0}
function renderDrones(){const el=$("#drones");if(!plans.length){el.innerHTML='<div class="dr" style="grid-template-columns:1fr">No flights needed today – every patch is fine. 🎉</div>';return}
 const byD={};plans.forEach(p=>{(byD[p.idx]=byD[p.idx]||[]).push(p)});const cap=D.policy.battery_wh,pct=w=>Math.max(0,Math.min(100,Math.round(w/cap*100))),FL=D.fleet||{};
 el.innerHTML=Object.keys(byD).map(k=>{const ps=byD[k].sort((x,y)=>x.start-y.start),cur=ps.find(p=>tNow<p.end)||ps[ps.length-1],st=posAt(cur,tNow),ix=ps.indexOf(cur),prev=ps[ix-1];
  let bat,msg=st.msg,charging=false;const frac=Math.max(0,Math.min(1,(tNow-cur.start)/Math.max(.1,cur.end-cur.start)));
  if(cur.soc&&!cur.demo){
   if(st.idle){if(prev&&prev.soc){const u=Math.max(0,Math.min(1,(tNow-prev.end)/Math.max(.1,cur.start-prev.end)));bat=pct(prev.soc.soc_end+(cur.soc.soc_start-prev.soc.soc_end)*u);charging=true;
     msg=FL.mode==="swap"?"🔋 Swapping to a fully charged pack…":`⚡ Recharging on its pad (${FL.rate_w} W for ${FL.turnaround_min} min, shown sped up)`}
     else{bat=pct(cur.soc.soc_start);msg="Waiting on its pad until the sky around it is clear"}}
   else bat=pct(cur.soc.soc_start-(cur.soc.soc_start-cur.soc.soc_end)*frac)}
  else{const used=cur.energy?cur.energy/cap*100:Math.min(60,cur.segs.length*8);bat=Math.max(0,Math.round(100-(cur.demo?frac*20:frac*used)))}
  return `<div class="dr"><div class="n">🚁 ${cur.demo?"You":names[cur.idx%5]}</div><div>${msg}${ps.length>1?` <span class="sub">(flight ${ix+1} of ${ps.length})</span>`:""}</div><div></div><div><div class="bat" title="battery"><div style="width:${bat}%;${charging?"background:var(--blue)":""}"></div></div><span class="sub">battery ${bat}% · pad ${String.fromCharCode(65+cur.pad)} · flies at ${cur.alt} m</span></div></div>`}).join("")}
(function(){const ms=D.mission.missions;if(!ms.length){$("#missionNote").textContent="No drone flights were needed today.";return}
 const patches=ms.reduce((a,m)=>a+m.targets.filter(t=>t[2]!=="via").length,0),waves=new Set(ms.map(m=>m.sortie||0)).size,drones=new Set(ms.map(m=>m.drone)).size,detours=ms.reduce((a,m)=>a+m.targets.filter(t=>t[2]==="via").length,0);
 $("#missionNote").textContent=`Mission for day ${D.mission.day}: ${patches} patches, ${drones} drone(s) in ${waves} wave(s) with a battery swap between waves. Drones flying together use their own pads and different heights, and every flight was replayed second-by-second in 3D to prove no two come too close`+(detours?`, and ${detours} detour point(s) route them around the no-fly zone`:"")+". Dashed lines are flight paths."})();
function setup(){L=fit(live);reset()}
let last=performance.now();function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(L)frame(dt);requestAnimationFrame(loop)}
$("#play").onclick=e=>{playing=!playing;e.target.textContent=playing?"⏸ Pause":"▶ Play";e.target.classList.toggle("on",playing)};
$("#restart").onclick=()=>{reset();playing=true;$("#play").textContent="⏸ Pause";$("#play").classList.add("on")};
[["s1",1],["s2",2],["s4",4]].forEach(([id,v])=>$("#"+id).onclick=()=>{speed=v;["s1","s2","s4"].forEach(i=>$("#"+i).classList.toggle("on",i===id))});
const tip=$("#tip");function showTip(e,txt){tip.style.display="block";tip.textContent=txt;tip.style.left=Math.min(innerWidth-240,e.clientX+14)+"px";tip.style.top=(e.clientY+14)+"px"}
function cellAt(cv,e){const r=cv.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)/r.width*N),y=N-1-Math.floor((e.clientY-r.top)/r.height*N);return (x>=0&&y>=0&&x<N&&y<N)?[x,y]:null}
live.onmousemove=e=>{const c=cellAt(live,e);if(!c)return tip.style.display="none";showTip(e,nofly.has(c.join(","))?"No-fly zone: drones are not allowed here.":`Patch (${c[0]},${c[1]}): ${describe(display[idx(c[0],c[1])])}`)};live.onmouseleave=()=>tip.style.display="none";
const toast=m=>{const t=$("#toast");t.textContent=m;t.style.display="block";clearTimeout(toast.h);toast.h=setTimeout(()=>t.style.display="none",2600)};
$("#dispatch").onclick=e=>{dispatchMode=!dispatchMode;e.target.classList.toggle("on",dispatchMode);live.style.cursor=dispatchMode?"crosshair":"default";if(dispatchMode)toast("Click any patch on the map to send a drone there.")};
live.onclick=e=>{if(!dispatchMode)return;const c=cellAt(live,e);if(!c)return;
 if(nofly.has(c.join(",")))return toast("🚫 That's a no-fly zone. The safety system would block this flight.");
 const cell=display[idx(c[0],c[1])],[n,m,p]=cell;let act=null;if(p>38)act="spray";else if(m<34)act="irrigate";
 if(!act)return toast("🌿 That patch is healthy. The AI wouldn't send a drone there!");
 const idn=100+demo.length,pl=buildPlan({drone:idn,alt:30+(D.policy.drones+demo.length)*20,targets:[[c[0],c[1],act]]},idn);pl.demo=true;
 shiftPlan(pl,tNow);demo.push(pl);plans.push(pl);
 toast(act==="spray"?"🌫 Drone dispatched to spray pests.":"💧 Drone dispatched to water this patch.")};
// ---------- TIME-LAPSE ----------
const lapse=$("#lapse"),H=D.history.length?D.history:[{day:D.day,cells:D.now}];let LP,mode="health",hi=H.length-1,lh=null;
const slider=$("#slider");slider.max=H.length-1;slider.value=hi;
function drawLapse(){LP=fit(lapse);drawField(LP.g,LP.s,H[hi].cells,mode,lh);$("#dayLabel").textContent=`Day ${H[hi].day}`+(H.length>1?` (${hi+1} of ${H.length})`:"")}
slider.oninput=()=>{hi=+slider.value;drawLapse()};
document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll("[data-mode]").forEach(x=>x.classList.toggle("on",x===b));drawLapse()});
let lt=null;$("#lapsePlay").onclick=e=>{if(lt){clearInterval(lt);lt=null;e.target.textContent="▶ Play";return}e.target.textContent="⏸ Pause";if(hi>=H.length-1)hi=0;lt=setInterval(()=>{hi++;if(hi>=H.length-1){hi=H.length-1;clearInterval(lt);lt=null;$("#lapsePlay").textContent="▶ Play"}slider.value=hi;drawLapse()},450)};
lapse.onmousemove=e=>{const c=cellAt(lapse,e);if(!c)return tip.style.display="none";lh=c;drawLapse();showTip(e,`Patch (${c[0]},${c[1]}) on day ${H[hi].day}: ${describe(H[hi].cells[idx(c[0],c[1])])}`)};lapse.onmouseleave=()=>{lh=null;tip.style.display="none";drawLapse()};
// ---------- feed, savings, trend ----------
const em={drone:"🚁",brain:"🧠",shield:"🛡️",warn:"⚠️",sat:"🛰️",wind:"🌬️"};
$("#feed").innerHTML=D.events.length?D.events.map(e=>`<li><span class="ico">${em[e.icon]||"•"}</span><span>${e.text}</span></li>`).join(""):"<li>Nothing yet – the first daily run will appear here.</li>";
const bar=(l,v,c,note)=>`<div class="row"><b>${l}</b><span>${Math.round(v)}% less</span></div><div class="bar"><div style="width:${Math.max(2,Math.min(100,v))}%;background:${c}"></div></div>`;
$("#saves").innerHTML=bar("💧 Water",k.water,"var(--blue)")+bar("🧴 Chemicals",k.chem,"var(--warn)")+`<div class="sub">Yield index <b>${k.yield}</b> (1.0 = no crop loss so far).</div>`;
(function(){const m=D.metrics.map(r=>r.yield_index);if(m.length<2)return;const lo=Math.min(...m),hi2=Math.max(...m),sp=(hi2-lo)||1;$("#spark").innerHTML=`<polyline fill="none" stroke="var(--acc)" stroke-width="2.5" vector-effect="non-scaling-stroke" points="${m.map((v,i)=>`${i*300/(m.length-1)},${42-(v-lo)/sp*38}`).join(" ")}"/>`})();
// ---------- real satellite view ----------
const SAT=D.satellite;
if(SAT&&SAT.scenes.length){$("#satCard").style.display="block";const sc=SAT.scenes,an=SAT.analysis;let si=sc.length-1,smode="ndvi";const cv=$("#sat"),sl=$("#satSlider");sl.max=sc.length-1;sl.value=si;
 const col=(v,m)=>{if(v==null)return null;if(m==="ndmi"){const t=Math.max(0,Math.min(1,(v+10)/65));return `hsl(${35+t*185},${45+t*20}%,${62-t*24}%)`}const t=Math.max(0,Math.min(1,(v-15)/70));return t<.45?`hsl(${28+t/.45*32},62%,${38+t/.45*12}%)`:`hsl(${60+(t-.45)/.55*75},${52+t*8}%,${46-(t-.45)*10}%)`};
 const hatch=(g,x,y,s)=>{g.fillStyle="#7d838a";g.fillRect(x,y,s,s);g.strokeStyle="rgba(255,255,255,.5)";g.lineWidth=1;g.beginPath();g.moveTo(x,y+s);g.lineTo(x+s,y);g.stroke()};
 const drawSat=()=>{const {g,s}=fit(cv),d=sc[si][smode];for(let x=0;x<N;x++)for(let y=0;y<N;y++){const v=d[idx(x,y)],px=x*s,py=(N-1-y)*s,c=col(v,smode);if(c){g.fillStyle=c;g.fillRect(px+.5,py+.5,s-1,s-1)}else hatch(g,px,py,s)}
  if(si===sc.length-1&&an.scouting){g.strokeStyle="#fff";g.lineWidth=2;an.scouting.slice(0,5).forEach(t=>{const [x,y]=t.cell;g.beginPath();g.arc(x*s+s/2,(N-1-y)*s+s/2,s*.6,0,7);g.stroke()})}
  $("#satDay").textContent=`${sc[si].date} · ${Math.round(sc[si].valid*100)}% of the field clear · ${si+1} of ${sc.length}`};
 sl.oninput=()=>{si=+sl.value;drawSat()};document.querySelectorAll("[data-sat]").forEach(b=>b.onclick=()=>{smode=b.dataset.sat;document.querySelectorAll("[data-sat]").forEach(x=>x.classList.toggle("on",x===b));drawSat()});
 cv.onmousemove=e=>{const c=cellAt(cv,e);if(!c)return tip.style.display="none";const a=sc[si].ndvi[idx(c[0],c[1])],w=sc[si].ndmi[idx(c[0],c[1])];
  showTip(e,a==null?"Patch ("+c+"): hidden by cloud on this date.":`Patch (${c[0]},${c[1]}): ${a>=70?"dense, healthy crop":a>=40?"moderate vigor":"sparse or stressed"} (vigor index ${(a/100).toFixed(2)}${w==null?"":`, leaf water ${(w/100).toFixed(2)}`})`)};cv.onmouseleave=()=>tip.style.display="none";
 const lat=an.latest,z=an.zones||[];
 $("#satText").innerHTML=`<p style="margin:0 0 8px"><b>Latest clear pass: ${lat.date}</b> (Sentinel-2). Average crop vigor <b>${an.ndvi.mean.toFixed(2)}</b> (1.0 = lush; below 0.4 = sparse or stressed).</p>`+
 (z.length?`<p style="margin:0 0 8px">🟤 <b>${z.length} struggling area${z.length>1?"s":""}</b> found, the largest covers ${z[0].cells} patches around (${z[0].centre.join(", ")}). These patches are far greener or browner than the rest of the field.</p>`:`<p style="margin:0 0 8px">🟢 No unusually weak areas in this image.</p>`)+
 (an.declining?`<p style="margin:0 0 8px">📉 ${an.declining} patches lost noticeable vigor since the previous pass (could be harvest/ripening, stress, or haze).</p>`:"")+
 (an.scouting&&an.scouting.length?`<p style="margin:0"><b>Check these spots first</b> (circled on the map): ${an.scouting.slice(0,5).map(t=>`(${t.cell.join(",")})`).join(" ")}</p>`:"");
 const ser=an.series;if(ser.length>1){const v=ser.map(r=>r.ndvi),lo=Math.min(...v),hi2=Math.max(...v),sp=(hi2-lo)||.05;$("#satSpark").innerHTML=`<polyline fill="none" stroke="var(--acc)" stroke-width="2.5" vector-effect="non-scaling-stroke" points="${v.map((q,i)=>`${i*300/(v.length-1)},${42-(q-lo)/sp*38}`).join(" ")}"/>`;$("#satSparkLbl").textContent=`${ser[0].date} → ${ser[ser.length-1].date}: ${ser[0].ndvi.toFixed(2)} → ${ser[ser.length-1].ndvi.toFixed(2)}`}
 drawSat();addEventListener("resize",drawSat)}
// ---------- airspace safety + fleet ----------
(function(){const lm=D.metrics[D.metrics.length-1]||{},P=D.policy,mis=D.mission.missions,F=D.fleet||{};
 const ratio=lm.traffic_min_ratio,ser=lm.traffic_mode==="serialized";
 $("#air").innerHTML=(mis.length?`<p style="margin:0 0 8px;font-size:18px">${ser?"🟡":"✅"} <b>Zero close calls</b>${ratio?`, with the closest pair never nearer than <b>${ratio.toFixed(2)}×</b> the required safe distance.`:"."}</p>`:`<p style="margin:0 0 8px;font-size:18px">✅ No flights today, so nothing to separate.</p>`)+
 `<ul class="sub" style="margin:0;padding-left:18px;display:grid;gap:4px"><li>Every drone has its <b>own pad</b>, ${P.pad_spacing_m} m apart.</li><li>Drones in the air together cruise at <b>different heights</b> (at least ${P.v_clear} m apart).</li><li>Each plan is <b>replayed second by second in 3D</b> before takeoff. It is rejected if two drones would ever be within ${P.h_clear} m sideways <i>and</i> ${P.v_clear} m vertically.</li>${lm.launch_stagger_s?`<li>Today the launches were <b>staggered by up to ${lm.launch_stagger_s} s</b> so no one climbs through another drone's path.</li>`:""}${ser?"<li><b>No safe overlap was found, so the drones flew one at a time.</b></li>":""}</ul>`;
 const dr=F.drones||[];
 $("#fleetCard").innerHTML=`<p style="margin:0 0 8px">${F.mode==="swap"?`🔋 Packs are <b>swapped</b> for charged spares between flights (${F.swap_min} min).`:`⚡ <b>Recharging on the pad</b> between flights at ${F.rate_w} W for ${F.turnaround_min} min.`} Everything is fully recharged overnight${lm.overnight_charge_hours?` (about ${lm.overnight_charge_hours} h of charging last night)`:""}.</p>`+
 (dr.length?`<div class="tiles" style="margin:8px 0">${dr.map((x,i)=>`<div class="tile" title="Battery wear: capacity shrinks slowly with use"><div class="k">${names[i%5]}</div><div class="v" style="font-size:22px">${Math.round(x.health*100)}%</div><div class="d">pack health · ${x.cycles.toFixed(1)} full cycles</div></div>`).join("")}</div>`:"")+
 (lm.fleet_energy_wh!=null?`<div class="sub">Today: <b>${Math.round(lm.fleet_energy_wh)} Wh</b> flown${lm.charged_between_flights_wh?`, <b>${Math.round(lm.charged_between_flights_wh)} Wh</b> recharged between flights`:""}. Lowest battery after landing: <b>${Math.round(lm.soc_min_pct||0)}%</b> (the safety reserve is kept).</div>`:"")})();
// ---------- wind & GPS ----------
(function(){const lm=D.metrics[D.metrics.length-1]||{},L2=D.policy.wind_lim||{},dn=a=>["N","NE","E","SE","S","SW","W","NW"][Math.round(((a%360)+360)%360/45)%8];
 const ws=lm.wind_ms,gu=lm.gust_ms,grounded=lm.grounded_by_wind,defer=lm.spray_deferred;
 const bar=(label,v,lim,col)=>`<div class="row"><span>${label}</span><b>${v==null?"–":v.toFixed(1)} / ${lim} m/s</b></div><div class="bar" style="height:10px"><div style="width:${Math.min(100,(v||0)/lim*100)}%;background:${(v||0)>lim?"var(--warn)":col}"></div></div>`;
 const status=ws==null?"No data yet.":grounded?"🔴 <b>Too windy: the fleet stayed on the ground today.</b> Work waits for a calmer day.":defer?`🟡 <b>Flying, but spraying is postponed</b> for ${defer} patches (wind would blow the spray away). Watering continues.`:"🟢 <b>Good flying conditions.</b>";
 $("#windCard").innerHTML=`<p style="margin:0 0 8px">${status}</p>`+(ws==null?"":`<div class="sub" style="margin-bottom:8px">Flight-window wind: <b>${ws.toFixed(1)} m/s</b> from the <b>${dn(lm.wind_from_deg)}</b>, gusting <b>${gu.toFixed(1)} m/s</b> (flights are planned for the calmer morning).</div>`+bar("Wind vs flight limit",ws,L2.max_flight_ms,"var(--acc)")+bar("Gusts vs limit",gu,L2.max_gust_ms,"var(--acc)")+bar("Wind vs spray limit",ws,L2.max_spray_ms,"var(--blue)"))+
 `<ul class="sub" style="margin:8px 0 0;padding-left:18px;display:grid;gap:3px"><li>Headwinds cost battery, tailwinds save it; every route is costed leg by leg.</li><li>Wind is stronger up high, so the top flight layer drops out first.</li><li>Gusts make the drones keep extra distance from each other.</li></ul>`;
 const tot=D.metrics.reduce((a,r)=>a+(r.gps_losses||0),0),down=lm.drones_grounded||0,days=D.metrics.reduce((a,r)=>a+(r.grounded_by_wind?1:0),0);
 $("#gpsCard").innerHTML=`<p style="margin:0 0 8px">${down?`🟠 <b>${down} drone${down>1?"s are":" is"} down in the field</b> waiting to be picked up.`:tot?"🟢 All drones are flying again.":"🟢 No GPS problems so far."}</p><div class="sub" style="margin-bottom:8px">GPS losses so far: <b>${tot}</b> · windy no-fly days: <b>${days}</b> of ${D.metrics.length}</div>`+
 `<ul class="sub" style="margin:0;padding-left:18px;display:grid;gap:3px"><li>Before takeoff a drone needs a strong GPS lock (at least 10 satellites), or it does not fly.</li><li>If GPS drops: <b>spraying stops instantly</b>, the drone waits ${D.policy.gps_grace_s} s for the signal, then <b>lands where it is</b>. It cannot navigate home without GPS, so it doesn't try.</li><li>Drones flying <b>below</b> a failing drone are sent home at once.</li><li>A landed drone is recovered by a person (about ${D.policy.gps_recovery_days} day) and its unfinished patches are re-planned.</li></ul>`})();
// ---------- briefing + money ----------
if(D.briefing&&D.briefing.length){$("#briefCard").style.display="block";$("#brief").innerHTML=D.briefing.map(t=>`<li><span class="ico">•</span><span>${t}</span></li>`).join("")}
(function(){const E=D.economics;if(!E)return;$("#moneyCard").style.display="block";
 $("#moneySub").textContent=`One season on ${E.hectares} hectares, using PLACEHOLDER prices (water, chemicals, crop value, drones). Replace them in the policy file with yours.`;
 const mx=Math.max(...E.rows.map(r=>r.revenue)),f=v=>"$"+Math.round(v).toLocaleString();
 $("#money").innerHTML=E.rows.map(r=>`<div class="brow${r.id==="agent-3"?" hl":""}"><b>${r.name}</b><div><span class="cap">Profit ${f(r.profit)} (${f(r.profit_per_ha)} per hectare)</span><div class="b"><div style="width:${Math.max(2,r.profit/mx*100)}%;background:var(--acc)"></div></div></div><div><span class="cap">Costs: water ${f(r.water_cost)} · spray ${f(r.spray_cost)} · fleet ${f(r.fleet_cost)}</span><div class="b"><div style="width:${Math.max(2,r.cost/mx*400)}%;background:var(--warn)"></div></div></div></div>`).join("");
 const ai=E.rows.find(r=>r.id==="agent-3"),cal=E.rows.find(r=>r.id==="calendar"),none=E.rows.find(r=>r.id==="none"),sm=E.rows.find(r=>r.id==="triggered");
 $("#moneyNote").innerHTML=`With these prices the drone crew earns <b>${f(ai.profit-cal.profit)}</b> more per season than the fixed schedule`+(E.payback_days?` and pays back the drones in about <b>${E.payback_days} days</b> of operation`:"")+`. `+(sm?`<b>The honest comparison is a smart farmer</b> who reads the same soil sensors and waters when it is dry: that farmer earns ${f(sm.profit)}, versus ${f(ai.profit)} for the drones (${f(ai.profit-sm.profit)} difference). ${E.payback_vs_smart_days?`Against that farmer the drones take about ${(E.payback_vs_smart_days/365).toFixed(0)} years to pay back`:"Against that farmer the drones never pay back"} under these prices: the drones' real edge is doing it automatically, not doing it better. `:"")+`A fixed schedule can even earn <i>less</i> than doing nothing when water and spray cost more than the crop they save${cal.profit<none.profit?" (it does here)":""}. <i>(Simulation + placeholder prices: a decision aid, not a forecast.)</i>`})();
// ---------- weather, sensors, workload, benchmark ----------
const W=D.weather,ic=r=>r>=10?"🌧️":r>=1?"🌦️":"☀️";
if(W&&W.today){const t=W.today,soon=W.forecast.slice(0,2).reduce((a,f)=>a+f.rain_mm,0);
 $("#wxsub").textContent="Source: "+(W.source==="synthetic"?"simulated seasonal climate":W.source);
 $("#wx").innerHTML=`<div class="row" style="font-size:18px"><span>${ic(t.rain_mm)} Today</span><b>${t.tmax.toFixed(0)}° / ${t.tmin.toFixed(0)}°C</b></div><div class="sub">${t.rain_mm.toFixed(1)} mm rain · crops use about ${t.et0_mm.toFixed(1)} mm of water a day</div>`+
 (W.forecast.length?`<div class="tiles" style="margin-top:10px">${W.forecast.map((f,i)=>`<div class="tile"><div class="k">${ic(f.rain_mm)} in ${i+1} day${i?"s":""}</div><div class="d">${f.tmax.toFixed(0)}°/${f.tmin.toFixed(0)}° · ${f.rain_mm.toFixed(1)} mm</div></div>`).join("")}</div><div class="sub" style="margin-top:8px">${soon>=10?"💧 Rain is coming, so drones hold off watering patches that aren't critical (saves water).":"No real rain soon, so drones water patches that are drying out."}</div>`:"")}
else $("#wx").textContent="No weather recorded yet.";
const lm=D.metrics[D.metrics.length-1]||{};
$("#sens").innerHTML=(lm.sensors_flagged||lm.sensors_quarantined)?`🛰 <b>${lm.sensors_flagged||0}</b> suspicious readings today were repaired from healthy neighbouring patches. <b>${lm.sensors_quarantined||0}</b> sensor(s) keep misbehaving and need maintenance.`:"🛰 All sensors look healthy: no suspicious readings today.";
(function(){const v=D.metrics.map(r=>Math.max(0,(r.targets||0)-(r.executed||0)));if(v.length)$("#sens").innerHTML+=`<div class="sub" style="margin-top:8px">${v[v.length-1]===0?"✅ The crew is keeping up: no patches left waiting today.":`⏳ ${v[v.length-1]} patches are waiting for a drone tomorrow.`}</div>`;if(v.length<2)return;const hi=Math.max(...v,1);$("#backlog").innerHTML=`<polyline fill="none" stroke="var(--warn)" stroke-width="2.5" vector-effect="non-scaling-stroke" points="${v.map((x,i)=>`${i*300/(v.length-1)},${42-x/hi*38}`).join(" ")}"/>`})();
const B=D.benchmark;
if(B){$("#benchCard").style.display="block";$("#benchSub").textContent=`Measured on ${B.seeds} different simulated farms (${B.patches} patches each) over a ${B.days}-day season. Every strategy faces exactly the same weather.`;
 const maxW=Math.max(...B.strategies.map(s=>s.water_mm)),cal=B.strategies.find(s=>s.id==="calendar"),ag=B.strategies.find(s=>s.id==="agent-3");
 $("#bench").innerHTML=B.strategies.map(s=>`<div class="brow${s.id==="agent-3"?" hl":""}"><b>${s.name}</b><div><span class="cap">Crop yield ${(s.yield*100).toFixed(1)}%</span><div class="b"><div style="width:${s.yield*100}%;background:var(--acc)"></div></div></div><div><span class="cap">Water ${s.water_mm} mm · sprays ${s.sprays}</span><div class="b"><div style="width:${Math.max(2,s.water_mm/maxW*100)}%;background:var(--blue)"></div></div></div></div>`).join("");
 const lessW=Math.round(100*(1-ag.water_mm/cal.water_mm)),lessS=Math.round(100*(1-ag.sprays/cal.sprays));
 let note=`<b>The AI crew keeps ${(ag.yield*100).toFixed(1)}% of the crop while using ${lessW}% less water and ${lessS}% fewer sprays than the fixed schedule.</b> Doing nothing loses ${((1-B.strategies[0].yield)*100).toFixed(0)}% of the crop. With only one flight a day the crew can't keep up, which is why flights per day matter.`;
 if(B.ml_value)note+=` The learning model adds only ${(B.ml_value.mean*100).toFixed(2)} yield points on top of simple rules here (better on ${B.ml_value.wins} farms): honest, but small in a simulation where stress is a clean threshold.`;
 if(B.faults&&B.faults.variants.length==2){const o=B.faults.variants[0],n=B.faults.variants[1];note+=` If ${Math.round(B.faults.rate*100)}% of sensors break, the sensor guard cuts wasted water by ${Math.round(100*(1-n.water_mm/o.water_mm))}%.`}
 $("#benchNote").innerHTML=note+" <i>(Simulation results, not field trials.)</i>"}
// ---------- theme + boot ----------
$("#theme").onclick=()=>{const r=document.documentElement,dark=(r.dataset.theme||(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light"))==="dark";r.dataset.theme=dark?"light":"dark";drawLapse()};
function boot(){setup();drawLapse()}
boot();addEventListener("resize",()=>{boot()});requestAnimationFrame(loop);
</script></body></html>"""
