"""Static dashboard (docs/dashboard.html): KPI tiles, trend sparklines, field heatmap, recent audit events.
Regenerated by the autopilot every cycle; no JS dependencies, works offline."""
import html
import json

from .config import ROOT
from .store import load_farm, read_jsonl
from .config import load_policy


def _spark(vals, w=260, h=48):
    if len(vals) < 2:
        return ""
    lo, hi = min(vals), max(vals)
    span = (hi - lo) or 1
    pts = " ".join(f"{i * w / (len(vals) - 1):.1f},{h - 4 - (v - lo) / span * (h - 8):.1f}" for i, v in enumerate(vals))
    return f'<svg viewBox="0 0 {w} {h}" width="100%" height="{h}"><polyline fill="none" stroke="var(--accent)" stroke-width="2" points="{pts}"/></svg>'


def _heat(farm):
    n, s = farm.size, 14
    cells = []
    for (x, y), c in farm.cells.items():
        g = max(0.0, min(1.0, (c.ndvi - 0.2) / 0.7))
        col = f"hsl({int(g * 110)},65%,{38 + int(g * 8)}%)"
        cells.append(f'<rect x="{x * s}" y="{y * s}" width="{s - 1}" height="{s - 1}" fill="{col}"><title>({x},{y}) NDVI {c.ndvi:.2f} moisture {c.moisture:.2f} pest {c.pest:.2f}</title></rect>')
    return f'<svg viewBox="0 0 {n * s} {n * s}" width="100%" style="max-width:420px">{"".join(cells)}</svg>'


def render(state_dir=None, policy=None):
    policy = policy or load_policy()
    rows = [r for r in read_jsonl("metrics.jsonl", state_dir) if r.get("ok") and not r.get("skipped")]
    audit = read_jsonl("audit.jsonl", state_dir)[-12:][::-1]
    farm = load_farm(policy["field"]["seed"], policy["field"]["size"], state_dir)
    last = rows[-1] if rows else {}
    series = lambda k: [r.get(k, 0) for r in rows[-60:]]
    tiles = [("Detection accuracy", f"{last.get('accuracy', 0):.1%}", "accuracy"),
             ("Water saved vs baseline", f"{last.get('water_saved_pct', 0)}%", "water_saved_pct"),
             ("Chemical saved vs baseline", f"{last.get('chem_saved_pct', 0)}%", "chem_saved_pct"),
             ("Yield index", f"{last.get('yield_index', 0)}", "yield_index")]
    tile_html = "".join(f'<div class="tile"><div class="k">{t}</div><div class="v">{v}</div>{_spark(series(k))}</div>' for t, v, k in tiles)
    ev = "".join(f"<tr><td>{html.escape(str(a.get('kind')))}</td><td>{html.escape(json.dumps({k: v for k, v in a.items() if k not in ('ts', 'kind', 'trace')})[:140])}</td></tr>" for a in audit)
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AgriDroneAI Dashboard</title><style>
:root{{--bg:#f6f7f4;--card:#fff;--fg:#1b2b1f;--mut:#667;--accent:#2f8f4e;--bd:#dde3da}}
@media(prefers-color-scheme:dark){{:root{{--bg:#121a14;--card:#1a251d;--fg:#e6efe8;--mut:#9ab;--accent:#5fd085;--bd:#2c3b30}}}}
body{{margin:0;padding:16px;background:var(--bg);color:var(--fg);font:15px system-ui,sans-serif}}
h1{{font-size:20px;margin:0 0 4px}}.sub{{color:var(--mut);margin-bottom:16px}}
.grid{{display:grid;gap:12px;grid-template-columns:repeat(auto-fit,minmax(220px,1fr))}}
.tile,.card{{background:var(--card);border:1px solid var(--bd);border-radius:10px;padding:12px}}
.k{{color:var(--mut);font-size:13px}}.v{{font-size:26px;font-weight:600}}
table{{width:100%;border-collapse:collapse;font-size:13px}}td{{padding:4px 6px;border-top:1px solid var(--bd);vertical-align:top;word-break:break-word}}
.row{{display:grid;gap:12px;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));margin-top:12px}}
</style></head><body>
<h1>AgriDroneAI</h1>
<div class="sub">Day {farm.day} · autonomy: <b>{html.escape(policy['autonomy_level'])}</b> · kill switch: <b>{'ENGAGED' if policy['kill_switch'] else 'off'}</b> · simulated data</div>
<div class="grid">{tile_html}</div>
<div class="row"><div class="card"><div class="k">Field health (NDVI) — hover a cell</div>{_heat(farm)}</div>
<div class="card"><div class="k">Recent agent decisions (audit log)</div><table>{ev}</table></div></div>
</body></html>"""


def write(state_dir=None):
    out = ROOT / "docs" / "dashboard.html"
    out.write_text(render(state_dir))
    return out
